#include "game.h"
#include <stdio.h>
#include <stdlib.h>
#include "gba.h"

//images
#include "images/kong.h"
#include "images/lose.h"
#include "images/goodGame.h"
#include "images/wood.h"
#include "images/jungle.h"
#include "images/startJungle.h"


/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START_SCREEN,
  PLAY_SCREEN,
  WIN,
  LOSE,
} GBAState;


// TODO: Use this somehow in the states below. When you press and
//       hold A (the z key in the emulator we recommend), it
//       should NOT cycle through all of the states!
int a_down = 0; // 0 equivalent to false, any non-zero value equivalent to true
int condition = 1; // turns to 0 if SELECT is preseed to play again
int a_pressed = 1; // turns to 0 to prevent game from resetting each time z is pressed

//Movement variables
int leftInt = 5;
int rightInt = 5;
int upInt = 5;
int downInt = 5;
int currentCol = 180;
int currentRow = 140;
int steps = 0;
int preventDisplayStep = 1;



// Purpose: allows the player to check if they hit an obstacle or not
// Implementation: checks whether the two image collided with each other
int collision(int kongRow, int kongCol, int woodRow, int woodCol) {
  if ((kongCol > woodCol) && (kongCol < woodCol + 40) && (kongRow > woodRow) && (kongRow < woodRow + 10)) {
    return 1;
  }
  if ((kongCol + 20 > woodCol) && (kongCol + 20 < woodCol + 40) && (kongRow > woodRow) && (kongRow < woodRow + 10)) {
    return 1;
  }
  if ((kongCol > woodCol) && (kongCol < woodCol + 40) && (kongRow + 25 > woodRow) && (kongRow + 25 < woodRow + 10)) {
    return 1;
  }
  if ((kongCol + 20 > woodCol) && (kongCol + 20 < woodCol + 40) && (kongRow + 25 > woodRow) && (kongRow + 25 < woodRow + 10)) {
    return 1;
  } else { 
    return 0;
  }
}

int collisionCheck(int currentRowKong, int currentColKong) {
  if (collision(currentRowKong, currentColKong, 5, 200) || collision(currentRowKong, currentColKong, 30, 160) || collision(currentRowKong, currentColKong, 20, 80) || collision(currentRowKong, currentColKong, 40, 15) || collision(currentRowKong, currentColKong, 60, 120) || collision(currentRowKong, currentColKong, 85, 40) || collision(currentRowKong, currentColKong, 95, 110) || collision(currentRowKong, currentColKong, 115, 15)) {
    return 1;
  } else {
    return 0;
  }
}

int checkWin(int currRow, int currCol) {
  if (collision(currRow, currCol, 0, 20)) {
    return 1;
  } else {
    return 0;
  }
}

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START_SCREEN;

  // springf()

  //Text String
  char startScreenText[] = "Welcome to Kong's Jungle";
  char startScreenDesc[] = "Press z To Continue";
  char goalText[] = "Bring Kong To The White Box";
  // char loseText[] = "YOU LOST! PLEASE PRESS backspace TO RESTART!";
  // char winText[] =  "GG! YOU WON. PRESS backspace TO RESTART!";


  // Text in sprintf
  char buffer[90];



  while (1) {
    waitForVBlank();
    currentButtons = BUTTONS;  // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START_SCREEN:
          drawFullScreenImageDMA(startJungle);
          drawCenteredString(20, 80, 80, 40, startScreenText, YELLOW);
          drawCenteredString(80, 80, 80, 40, startScreenDesc, WHITE);
          state = PLAY_SCREEN;
          break;

      case PLAY_SCREEN:
          if (KEY_DOWN(BUTTON_A, currentButtons) && a_pressed) {
            drawFullScreenImageDMA(jungle);
            drawImageDMA(140, 180, 20, 25, kong);
            drawImageDMA(5, 200, 40, 10, wood); // top rightmost log
            drawImageDMA(30, 160, 40, 10, wood); // top 2nd rightmost log
            drawImageDMA(20, 80, 40, 10, wood); // top middle log
            drawImageDMA(40, 15, 40, 10, wood); // top leftmost log
            drawImageDMA(60, 120, 40, 10, wood); // top 3rd right log
            drawImageDMA(85, 40, 40, 10, wood); // 2nd left log
            drawImageDMA(95, 110, 40, 10, wood); // last right log
            drawImageDMA(115, 15, 40, 10, wood); // left last log
            drawRectDMA(0, 20, 40, 10, WHITE); // the goal white box
            drawString(140, 15, goalText, WHITE); // the goal text
            // if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
            //   // populateScreen(wood, jungle);
            //   drawImageDMA(140, currentCol - leftInt, 20, 25, kong);
            //   drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
            //   drawString(140, 15, goalText, WHITE); // the goal text
            a_down = 1;
            a_pressed = 0;
            break;
        } else if (a_down && !a_pressed) {
            if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
              if (currentCol - leftInt <= 0) {
                currentCol = 0;
                populateScreen(wood, jungle);
                drawImageDMA(currentRow, currentCol, 20, 25, kong);
                drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
                drawString(140, 15, goalText, WHITE); // the goal text
              } else {
                populateScreen(wood, jungle);
                drawImageDMA(currentRow, currentCol - leftInt, 20, 25, kong);
                drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
                drawString(140, 15, goalText, WHITE); // the goal text
                currentCol = currentCol - leftInt;
                steps++;
              }
              if (collisionCheck(currentRow, currentCol) == 1) {
                state = LOSE;
                break;
              } else if (checkWin(currentRow, currentCol) == 1){
                state = WIN;
                break;
              }
              break;
            } 
            if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
              if (currentCol + rightInt >= 220) {
                currentCol = 220;
                populateScreen(wood, jungle);
                drawImageDMA(currentRow, currentCol, 20, 25, kong);
                drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
                drawString(140, 15, goalText, WHITE); // the goal text
              } else {
                populateScreen(wood, jungle);
                drawImageDMA(currentRow, currentCol + rightInt, 20, 25, kong);
                drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
                drawString(140, 15, goalText, WHITE); // the goal text
                currentCol = currentCol + rightInt;
                steps++;
              }
              if (collisionCheck(currentRow, currentCol) == 1) {
                state = LOSE;
                break;
              } else if (checkWin(currentRow, currentCol) == 1) {
                state = WIN;
                break;
              }
              break;
            }
            if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
              if (currentRow - upInt <= 0) {
                currentRow = 0;
                populateScreen(wood, jungle);
                drawImageDMA(currentRow, currentCol, 20, 25, kong);
                drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
                drawString(140, 15, goalText, WHITE); // the goal text
              } else {
                populateScreen(wood, jungle);
                drawImageDMA(currentRow - upInt, currentCol, 20, 25, kong);
                drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
                drawString(140, 15, goalText, WHITE); // the goal text
                currentRow = currentRow - upInt;
                steps++;
              }
              if (collisionCheck(currentRow, currentCol) == 1) {
                state = LOSE;
                break;
              } else if (checkWin(currentRow, currentCol) == 1) {
                state = WIN;
                break;
              }
              break;
            }
            if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
              if (currentRow + downInt >= 135) {
                currentRow = 135;
                populateScreen(wood, jungle);
                drawImageDMA(currentRow, currentCol, 20, 25, kong);
                drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
                drawString(140, 15, goalText, WHITE); // the goal text
              } else {
                populateScreen(wood, jungle);
                drawImageDMA(currentRow + downInt, currentCol, 20, 25, kong);
                drawRectDMA(0, 20, 30, 10, WHITE); // the goal white box
                drawString(140, 15, goalText, WHITE); // the goal text
                currentRow = currentRow + downInt;
                steps++;
              }
              if (collisionCheck(currentRow, currentCol) == 1) {
                state = LOSE;
                break;
              } else if (checkWin(currentRow, currentCol) == 1) {
                state = WIN;
                break;
              }
              break;
            }  
          } 
            
          sprintf(buffer, "STEPS: %d", steps);
          drawString(95, 180, buffer, WHITE);
          break;
          
      case WIN:
        drawFullScreenImageDMA(goodGame);
        
        state = WIN;
        break;

      case LOSE:
        drawFullScreenImageDMA(lose);
        
        state = LOSE;
        break;
    }
    
    if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
      drawFullScreenImageDMA(startJungle);
      state = START_SCREEN;
      condition = 0;
      a_pressed = 1;
      currentRow = 140;
      currentCol = 180;
      steps = 0;
      }

    previousButtons = currentButtons;  // Store the current state of the buttons
  }

  return 0;
}
